exclude:
  - .venv
  - venv
  - uv_cache
  - .cache
  - .cache/uv
  - build
  - dist
  - __pycache__
  - .pytest_cache
  - .mypy_cache
  - node_modules

# Optional: Only scan your application code
# Uncomment if you want absolute precision for only the specific directories
# include:
#   - src
#   - tests
